// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tellerapi/v1/tellerapi.proto

package tellerapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TGreeterService_TSayHello_FullMethodName = "/tellerapi.v1.TGreeterService/TSayHello"
)

// TGreeterServiceClient is the client API for TGreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type TGreeterServiceClient interface {
	// Sends a greeting
	TSayHello(ctx context.Context, in *TSayHelloRequest, opts ...grpc.CallOption) (*TSayHelloResponse, error)
}

type tGreeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTGreeterServiceClient(cc grpc.ClientConnInterface) TGreeterServiceClient {
	return &tGreeterServiceClient{cc}
}

func (c *tGreeterServiceClient) TSayHello(ctx context.Context, in *TSayHelloRequest, opts ...grpc.CallOption) (*TSayHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TSayHelloResponse)
	err := c.cc.Invoke(ctx, TGreeterService_TSayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TGreeterServiceServer is the server API for TGreeterService service.
// All implementations must embed UnimplementedTGreeterServiceServer
// for forward compatibility.
//
// The greeting service definition.
type TGreeterServiceServer interface {
	// Sends a greeting
	TSayHello(context.Context, *TSayHelloRequest) (*TSayHelloResponse, error)
	mustEmbedUnimplementedTGreeterServiceServer()
}

// UnimplementedTGreeterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTGreeterServiceServer struct{}

func (UnimplementedTGreeterServiceServer) TSayHello(context.Context, *TSayHelloRequest) (*TSayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TSayHello not implemented")
}
func (UnimplementedTGreeterServiceServer) mustEmbedUnimplementedTGreeterServiceServer() {}
func (UnimplementedTGreeterServiceServer) testEmbeddedByValue()                         {}

// UnsafeTGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TGreeterServiceServer will
// result in compilation errors.
type UnsafeTGreeterServiceServer interface {
	mustEmbedUnimplementedTGreeterServiceServer()
}

func RegisterTGreeterServiceServer(s grpc.ServiceRegistrar, srv TGreeterServiceServer) {
	// If the following call pancis, it indicates UnimplementedTGreeterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TGreeterService_ServiceDesc, srv)
}

func _TGreeterService_TSayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TGreeterServiceServer).TSayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TGreeterService_TSayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TGreeterServiceServer).TSayHello(ctx, req.(*TSayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TGreeterService_ServiceDesc is the grpc.ServiceDesc for TGreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TGreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tellerapi.v1.TGreeterService",
	HandlerType: (*TGreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TSayHello",
			Handler:    _TGreeterService_TSayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tellerapi/v1/tellerapi.proto",
}
