name: Beta # 工作流程的名稱

on: # 觸發條件
  workflow_dispatch:

jobs:
  version: # 工作名稱
    uses: ./.github/workflows/tag-beta.yaml
    permissions:
      contents: write
    secrets: inherit

  package:
    needs: version
    uses: ./.github/workflows/packages-pnpm.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
      prod-version: ${{ needs.version.outputs.prod-version }}
      environment: beta