# dev 是開發階段，打tag部署
name: Dev # 工作流程的名稱

on: # 觸發條件
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev.*'
jobs:
  version: # 工作名稱
    uses: ./.github/workflows/tag-dev.yaml
    permissions:
      contents: write
    secrets: inherit

  package:
    needs: version
    uses: ./.github/workflows/packages-pnpm.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
      prod-version: ${{ needs.version.outputs.prod-version }}
      environment: dev