# Production 是上線階段，當releases/** 或是 bugfix/*分支，使用pull request 方式合到release/*時，打包Alpha進行部署並通知QAteam測試
name: Production  # 工作流程的名稱

on:  # 觸發條件
  pull_request:  # 當有 Push 事件時觸發
    branches:  # 僅針對特定分支
    - main
    types:
    - closed       # PR 關閉才會執行

jobs:
  version: # 工作名稱
    uses: ./.github/workflows/tag-prod.yaml
    permissions:
      contents: write
    secrets: inherit

  package:
    needs: version
    uses: ./.github/workflows/packages-pnpm.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
      prod-version: ${{ needs.version.outputs.version }}
      environment: prod