# Production 是上線階段，當releases/** 或是 bugfix/*分支，使用pull request 方式合到release/*時，打包Alpha進行部署並通知QAteam測試
name: Production  # 工作流程的名稱

on:  # 觸發條件
  pull_request:  # 當有 Push 事件時觸發
    branches:  # 僅針對特定分支
    - main
    types:
    - closed       # PR 關閉才會執行

jobs:

  version:  # 工作名稱
    uses: toward-the-stars/workflows/.github/workflows/tag-prod.yaml@main
    permissions:
      contents: write
    secrets: inherit

  web:
    needs: version
    uses: ./.github/workflows/packages-pnpm.yaml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
      environment: prod

  ecr:
    needs:
      - version
      - web
    uses: toward-the-stars/workflows/.github/workflows/ecr-web-nginx.yaml@main
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      version: ${{ needs.version.outputs.version }}
      environment: prod
      role-to-assume: ${{ vars.AWS_PROD_ARTIFAT_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ github.repository }}

  helm:
    needs:
      - version
      - ecr
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_DEPLOYMENT_TOKEN }}
          repository: toward-the-stars/stars-helm
          event-type: ${{ github.repository }}
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "prod-version": "${{ needs.version.outputs.version }}",
              "stage": "prod",
              "version": "${{ needs.version.outputs.version }}",
              "role-to-assume": "${{ vars.AWS_PROD_ARTIFAT_ROLE_ARN }}"
            }